# Generated by Django 3.0.6 on 2023-06-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=30)),
                ('c_id', models.CharField(max_length=40)),
                ('c_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('branch', models.CharField(max_length=20)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.IntegerField()),
                ('school_name', models.CharField(max_length=30)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
